# Generated by Django 5.0.6 on 2024-10-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenusDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('table_name', models.CharField(max_length=200)),
                ('menu_type', models.CharField(choices=[('models', 'Models'), ('sqlviews', 'Sql Views'), ('auth', 'Authentication'), ('customapi', 'Custom API'), ('coreapi', 'Core API'), ('cmspage', 'Cms Page')], max_length=200)),
                ('authentication_key_value', models.CharField(max_length=200)),
                ('starter_menu', models.CharField(blank=True, choices=[('user_master', 'User Master'), ('roles_master', 'Roles Master'), ('user_privilege', 'User Privilege'), ('menu_elements', 'Menu Elements'), ('menu_privilege', 'Menu Privilege')], max_length=200, null=True)),
                ('api_method', models.CharField(max_length=200)),
                ('doc_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=200)),
                ('api_url', models.CharField(max_length=200)),
                ('favicon_caption', models.CharField(max_length=200)),
                ('favicon_logo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='StudioMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(blank=True, max_length=200, null=True)),
                ('menu_uid', models.CharField(max_length=200)),
                ('menu_href', models.CharField(blank=True, max_length=200, null=True)),
                ('menu_ui_code', models.CharField(blank=True, max_length=200, null=True)),
                ('icon_class', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('menu_app_bar', models.CharField(blank=True, max_length=200, null=True)),
                ('menu_order', models.IntegerField(blank=True, null=True)),
                ('menu_code', models.CharField(blank=True, max_length=200, null=True)),
                ('menu_type', models.CharField(blank=True, max_length=200, null=True)),
                ('menu_parent_id', models.IntegerField(blank=True, null=True)),
                ('psk_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
